#!/bin/bash
# Quick guide for using Railway CLI

echo "🚂 Railway CLI Quick Guide"
echo ""
echo "1. Authenticate (opens browser):"
echo "   railway login"
echo ""
echo "2. Link to your project:"
echo "   cd /Users/damian/Projects/productivity-mcp-server"
echo "   railway link"
echo ""
echo "3. Get service URL:"
echo "   railway domain"
echo "   # or"
echo "   railway status"
echo ""
echo "4. View all services:"
echo "   railway service"
echo ""
echo "5. View logs:"
echo "   railway logs"
echo ""
echo "6. Deploy:"
echo "   railway up"
echo ""
echo "Alternative: Use the Python script with your API token:"
echo "   export RAILWAY_API='your-token'"
echo "   python3 scripts/get_railway_url.py"
